services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_DB: 'postgres_db'
      POSTGRES_USER: 'db_user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: go.dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgres://db_user:password@db:5432/postgres_db'



volumes:
  db-data: {}
